---
version: 2

builds:
  - id: build_cgo
    binary: hister
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=netgo,osusergo
    ldflags:
      - -s -w
    ignore:
      - goos: windows
        goarch: arm64
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CGO_LDFLAGS=-lssp -static
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

archives:
  - formats: ['tar.gz', 'binary']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: hister
    repository:
      owner: asciimoo
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN }}"
    description: "Your own search engine"
    homepage: "https://github.com/asciimoo/hister"
    license: "AGPL-3.0-or-later"
    install: |
      bin.install "hister"
    test: |
      system "#{bin}/hister", "--version"
